#!/bin/bash

VPR_OPTIONS="@VPR_ARGS@"

function parse_args {

     OPTS=d:e:p:n:
     LONGOPTS=device:,eblif:,pcf:,net

     PARSED_OPTS=`getopt --options=${OPTS} --longoptions=${LONGOPTS} --name $0 -- $@`
     eval set -- ${PARSED_OPTS}

     DEVICE=""
     DEVICE_NAME=""
     EBLIF=""
     PCF=""
     NET=""

     while true; do
          case "$1" in
               -d|--device)
                    DEVICE=$2
                    shift 2
                    ;;
               -e|--eblif)
                    EBLIF=$2
                    shift 2
                    ;;
               -p|--pcf)
                    PCF=$2
                    shift 2
                    ;;
               -n|--net)
                    NET=$2
                    shift 2
                    ;;
               --)
                    break
                    ;;
          esac
     done

     if [ -z $DEVICE ]; then
          echo "Please provide device name"
          exit 1
     fi

     if [ -z $EBLIF ]; then
          echo "Please provide blif file name"
          exit 1
     fi

     export DEVICE=$DEVICE
     export EBLIF=$EBLIF
     export PCF=$PCF
     export NET=$NET

     export ARCH_DIR=`realpath ${MYPATH}/../share/arch/$DEVICE`
     ARCH_DEF=${ARCH_DIR}/arch.timing.xml
     export  LOOKAHEAD=${ARCH_DIR}/rr_graph_${DEVICE}.lookahead.bin
     export RR_GRAPH=${ARCH_DIR}/rr_graph_${DEVICE}.rr_graph.real.xml
     export PLACE_DELAY=${ARCH_DIR}/rr_graph_${DEVICE}.place_delay.bin
     export DEVICE_NAME=`echo $DEVICE | sed -n 's/_/-/p'`
}

function run_vpr {

     vpr ${ARCH_DEF} \
         ${EBLIF} \
         --device ${DEVICE_NAME} \
         ${VPR_OPTIONS} \
         --read_rr_graph ${RR_GRAPH} \
         --read_router_lookahead ${LOOKAHEAD} \
         --read_placement_delay_lookup ${PLACE_DELAY} \
         $@

}

function run_genfasm {

     genfasm ${ARCH_DEF} \
         ${EBLIF} \
         --device ${DEVICE_NAME} \
         ${VPR_OPTIONS} \
         --read_rr_graph ${RR_GRAPH} \
         $@

}
