#!/bin/bash

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

source ${MYPATH}/env
source ${VPRPATH}/vpr_common

parse_args $@

export OUT_NOISY_WARNINGS=noisy_warnings-${DEVICE}_fasm.log

run_genfasm

mv vpr_stdout.log fasm.log
