MUX_COMMENT = F8MUX is used to create a LUT8 from two LUT7s (which are built out of two LUT6s themselves).
MUX_TYPE = logic
MUX_OUTFILE = f8mux
MUX_NAME = F8MUX
MUX_WIDTH = 2
MUX_SPLIT_INPUTS = 1
MUX_SPLIT_SELECTS = 1
