set_property LOC W5 [get_ports {i_clk}]
set_property LOC W7 [get_ports {i_clkb}]

set_property LOC R3 [get_ports {i_rst}]
set_property LOC T3 [get_ports {i_ce}]
set_property LOC T1 [get_ports {o_q1}]
set_property LOC U1 [get_ports {o_q2}]

set_property LOC G18 [get_ports {io[0]}]
set_property LOC F18 [get_ports {io[1]}]
set_property LOC E19 [get_ports {io[2]}]
set_property LOC H19 [get_ports {io[3]}]
set_property LOC G19 [get_ports {io[4]}]
set_property LOC H17 [get_ports {io[5]}]
set_property LOC G17 [get_ports {io[6]}]
set_property LOC K19 [get_ports {io[7]}]
set_property LOC J19 [get_ports {io[8]}]
set_property LOC J17 [get_ports {io[9]}]
set_property LOC J18 [get_ports {io[10]}]
set_property LOC L18 [get_ports {io[11]}]
