#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

PCF=$1
EBLIF=$2
NET=$3
PART=$4
DEVICE=$5
ARCH_DEF=$6

CHANNELS=`realpath ${MYPATH}/../share/arch/${DEVICE}/channels.db`
PINMAP=`realpath ${MYPATH}/../share/arch/${DEVICE}/pinmap.csv`
IOGEN=`realpath ${MYPATH}/python/create_ioplace.py`
#CONSTR_GEN=`realpath ${MYPATH}/python/prjxray_create_place_constraints.py`
PROJECT=$(basename -- "$EBLIF")
IOPLACE_FILE="${PROJECT%.*}_io.place"

python3 ${IOGEN} --pcf $PCF --blif $EBLIF --map $PINMAP --net $NET > ${IOPLACE_FILE}

