#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

source ${MYPATH}/env
echo "Writing bitstream ..."

FRAMES2BIT=`realpath ${VPRPATH}/xc7frames2bit`

OPTS=d:f:b:p:
LONGOPTS=device:,fasm:,bit:,part:

PARSED_OPTS=`getopt --options=${OPTS} --longoptions=${LONGOPTS} --name $0 -- $@`
eval set -- ${PARSED_OPTS}

DEVICE=""
FASM=""
BIT=""
PART="ql-eos-s3"

while true; do
	case "$1" in
		-d|--device)
			DEVICE=$2
			shift 2
			;;
		-p|--part)
			PART=$2
			shift 2
			;;
		-f|--fasm)
			FASM=$2
			shift 2
			;;
		-b|--bit)
			BIT=$2
			shift 2
			;;
		--)
			break
			;;
	esac
done

if [ -z $DEVICE ]; then
	echo "Please provide device name"
	exit 1
fi

if [ -z $FASM ]; then
	echo "Please provide fasm file name"
	exit 1
fi

if [ -z $BIT ]; then
	echo "Please provide bit file name"
	exit 1
fi

qlfasm ${FASM} ${BIT}

