#!/bin/bash
set -e

MYPATH=$(dirname "$(readlink -f "$BASH_SOURCE")")


source ${MYPATH}/env

JLINK2HEADER=`readlink -f ${MYPATH}/../bin/python/bitstream_to_header.py`


python3 ${JLINK2HEADER} ${TOP_F}.bit ../${TOP_F}_bit.h
