# Defaults for the fake testarch architecture.

DEVICE_SUBARCH ?= clutff-unidir-s4
DEVICE_DIR = ../testarch/devices/$(DEVICE_SUBARCH)/
DEVICE ?= 2x4
YOSYS_SCRIPT ?= synth; abc -lut 4;
RR_PATCH_TOOL ?= $(PWD)/../utils/testarch_graph.py
RR_PATCH_CMD ?= \
	$(RR_PATCH_TOOL)
