# Defaults for the iCE40 architecture.

DEVICE_DIR = ../ice40/devices/
DEVICE_TYPE ?= tile-routing-virt
DEVICE ?= LP384
YOSYS_SCRIPT ?= synth_ice40 -nodffe -nocarry; ice40_opt -unlut; abc -lut 4;
RR_PATCH_TOOL ?= $(PWD)/../ice40/utils/icebox-routing-import.py
RR_PATCH_CMD ?= \
	$(RR_PATCH_TOOL)
