# Defaults for the iCE40 architecture.

ARCH_DIR = ../artix7/arch/
ARCH_TYPE ?= xc7a50t-roi-virt
DEVICE ?= xc7a50t-test
YOSYS_SCRIPT ?= synth_xilinx;
RR_PATCH_TOOL ?= $(PWD)/../artix7/utils/prjxray-routing-import.py
RR_PATCH_CMD ?= \
	$(RR_PATCH_TOOL) \
	--database $(PWD)/../third_party/prjxray-db/artix7/ \
	--start_x 35 --end_x 38 --start_y 1 --end_y 3
