load('//make:build_defs.bzl', 'v2x')

v2x(
    name = 'carry4_split',
    srcs = [
        'carry4_split.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nmux:carry4_amux.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nmux:carry4_bmux.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nmux:carry4_cmux.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nmux:carry4_dmux.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nxor:carry4_axor.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nxor:carry4_bxor.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nxor:carry4_cxor.sim.v',
        '//artix7/primitives/slicel/carry4_modes/carry4_split/carry4_Nxor:carry4_dxor.sim.v',
        ],
    )

