#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

PCF=$1
EBLIF=$2
NET=$3
PART=$4
DEVICE=$5
ARCH_DEF=$6

VPR_GRID_MAP=`realpath ${MYPATH}/../share/symbiflow/arch/${DEVICE}/vpr_grid_map.csv`
PINMAP=`realpath ${MYPATH}/../share/symbiflow/arch/${DEVICE}/${PART}/pinmap.csv`
IOGEN=`realpath ${MYPATH}/python/prjxray_create_ioplace.py`
CONSTR_GEN=`realpath ${MYPATH}/python/prjxray_create_place_constraints.py`
PROJECT=$(basename -- "$EBLIF")
IOPLACE_FILE="${PROJECT%.*}.ioplace"

python3 ${IOGEN} --pcf $PCF --blif $EBLIF --map $PINMAP --net $NET > ${IOPLACE_FILE}
python3 ${CONSTR_GEN} --net $NET --arch ${ARCH_DEF} --blif $EBLIF --vpr_grid_map ${VPR_GRID_MAP} --input ${IOPLACE_FILE} > constraints.place

