MUX_GEN_OUTPUTS := \
	$(INC_DIR)/$(MUX_OUTFILE).model.xml \
	$(INC_DIR)/$(MUX_OUTFILE).pb_type.xml \
	$(INC_DIR)/$(MUX_OUTFILE).sim.v

MUX_GEN_CMD = $(realpath $(UTILS_DIR)/mux_gen.py)
MUX_GEN_LIB = $(realpath $(UTILS_DIR)/lib)
MUX_GEN_FILES = $(wildcard $(MUX_GEN_LIB)/*.py)

$(MUX_GEN_OUTPUTS): $(MUX_GEN_CMD) $(MUX_GEN_LIB) $(MUX_GEN_FILES)

include $(TOP_DIR)/make/mux-args.mk

$(MUX_GEN_OUTPUTS): INC_DIR := $(INC_DIR)
$(MUX_GEN_OUTPUTS): MUX_GEN_CMD := $(MUX_GEN_CMD)
$(MUX_GEN_OUTPUTS): MUX_GEN_ARGS := $(MUX_GEN_ARGS)

$(MUX_GEN_OUTPUTS): $(THIS_FILE)

$(MUX_GEN_OUTPUTS):
	@cd $(INC_DIR); $(MUX_GEN_CMD) $(MUX_GEN_ARGS)

OUTPUTS += $(MUX_GEN_OUTPUTS)
