#!/bin/bash
set -e

PYTHON3=`which python3`

MYPATH=$(dirname "$(readlink -f "$BASH_SOURCE")")

source ${MYPATH}/env

BIT2OPENOCD="${PYTHON3} -m quicklogic_fasm.bitstream_to_openocd"

echo "Converting bitstream to OpenOCD script"
${BIT2OPENOCD} $@
