#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

source ${MYPATH}/env
source ${VPRPATH}/vpr_common

parse_args $@

REPACK=`realpath ${MYPATH}/python/repacker/repack.py`

DESIGN=${EBLIF/.eblif/}
RULES=${ARCH_DIR}/${DEVICE_1}.repacking_rules.json

if [ -z "${JSON}" ];then
python3 ${REPACK} \
  --vpr-arch ${ARCH_DEF} \
  --repacking-rules ${RULES} \
  --eblif-in ${DESIGN}.eblif \
  --net-in ${DESIGN}.net \
  --place-in ${DESIGN}.place \
  --eblif-out ${DESIGN}.repacked.eblif \
  --net-out ${DESIGN}.repacked.net \
  --place-out ${DESIGN}.repacked.place \
  --absorb_buffer_luts on \
  >repack.log 2>&1
else	
python3 ${REPACK} \
  --vpr-arch ${ARCH_DEF} \
  --repacking-rules ${RULES} \
  --repacking-constraints ${JSON} \
  --eblif-in ${DESIGN}.eblif \
  --net-in ${DESIGN}.net \
  --place-in ${DESIGN}.place \
  --eblif-out ${DESIGN}.repacked.eblif \
  --net-out ${DESIGN}.repacked.net \
  --place-out ${DESIGN}.repacked.place \
  --absorb_buffer_luts on \
  >repack.log 2>&1
fi
