#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

PCF=$1
EBLIF=$2
NET=$3
PART=$4
DEVICE=$5
ARCH_DEF=$6

if ! [[ "$PART" =~ ^(PU64|WR42|PD64)$ ]]; then 
	 PINMAPCSV="pinmap_PD64.csv"
	 CLKMAPCSV="clkmap_PD64.csv"
else
     PINMAPCSV="pinmap_${PART}.csv"
     CLKMAPCSV="clkmap_${PART}.csv"
fi

echo "PINMAP FILE : $PINMAPCSV"
echo "CLKMAP FILE : $CLKMAPCSV"

PINMAP=`realpath ${MYPATH}/../share/arch/${DEVICE}/${PINMAPCSV}`
CLKMAP=`realpath ${MYPATH}/../share/arch/${DEVICE}/${CLKMAPCSV}`
IOGEN=`realpath ${MYPATH}/python/create_ioplace.py`
PLACEGEN=`realpath ${MYPATH}/python/create_place_constraints.py`
CONSTR_GEN=`realpath ${MYPATH}/python/eos_s3_iomux_config.py`
PROJECT=$(basename -- "$EBLIF")
IOPLACE_FILE="${PROJECT%.*}_io.place"
PLACE_FILE="${PROJECT%.*}_constraints.place"
IOMUX_JLINK="${PROJECT%.*}_iomux.jlink"
IOMUX_OPENOCD="${PROJECT%.*}_iomux.openocd"
IOMUX_BINARY="${PROJECT%.*}_iomux.bin"

python3 ${IOGEN} --pcf $PCF --blif $EBLIF --map $PINMAP --net $NET > ${IOPLACE_FILE}
python3 ${PLACEGEN} --blif $EBLIF --map $CLKMAP -i ${IOPLACE_FILE} > ${PLACE_FILE}
python3 ${CONSTR_GEN} --eblif $EBLIF --pcf $PCF --map $PINMAP --output-format=jlink > ${IOMUX_JLINK}
python3 ${CONSTR_GEN} --eblif $EBLIF --pcf $PCF --map $PINMAP --output-format=openocd > ${IOMUX_OPENOCD}
python3 ${CONSTR_GEN} --eblif $EBLIF --pcf $PCF --map $PINMAP --output-format=binary > ${IOMUX_BINARY}
