#!/bin/bash
set -e

PYTHON3=`which python3`

MYPATH=$(dirname "$(readlink -f "$BASH_SOURCE")")

source ${MYPATH}/env

BIT2BINARY="${PYTHON3} -m quicklogic_fasm.bitstream_to_binary"

echo "Converting bitstream to flashable binary format"
${BIT2BINARY} $@
