#!/bin/bash
set -e

PYTHON3=`which python3`

MYPATH=$(dirname "$(readlink -f "$BASH_SOURCE")")

source ${MYPATH}/env

BIT2HEADER="${PYTHON3} -m quicklogic_fasm.bitstream_to_header"

echo "Converting bitstream to C Header"
${BIT2HEADER} $@
