#!/bin/bash
set -e

PYTHON3=`which python3`

MYPATH=$(dirname "$(readlink -f "$BASH_SOURCE")")

source ${MYPATH}/env

BIT2JLINK="${PYTHON3} -m quicklogic_fasm.bitstream_to_jlink"

echo "Converting bitstream to JLink script"
${BIT2JLINK} $@
