#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

OPTS=d:P:p:b:
LONGOPTS=device:,part:,pcf:,bit:,

PARSED_OPTS=`getopt --options=${OPTS} --longoptions=${LONGOPTS} --name $0 -- "$@"`
eval set -- "${PARSED_OPTS}"

DEVICE=""
PART=""
PCF=""
BIT=""

while true; do
	case "$1" in
		-d|--device)
			DEVICE=$2
			shift 2
			;;
		-P|--part)
			PART=$2
			shift 2
			;;
		-p|--pcf)
			PCF=$2
			shift 2
			;;
		-b|--bit)
			BIT=$2
			shift 2
			;;
		--)
			break
			;;
	esac
done

if [ -z $DEVICE ]; then
    echo "Please provide device name"
	exit 1
fi

if [ -z $BIT ]; then
	echo "Please provide an input bistream file name"
	exit 1
fi


# Run fasm2bels
if [[ "$DEVICE" =~ ^(ql-eos-s3|ql-pp3e)$ ]]; then

    VPR_DB=`readlink -f ${MYPATH}/../share/symbiflow/arch/${DEVICE}_wlcsp/db_phy.pickle`
    FASM2BELS=`readlink -f ${MYPATH}/../bin/python/fasm2bels.py`
    FASM2BELS_DEVICE=${DEVICE/ql-/}
    VERILOG_FILE="${BIT}.v"
    PCF_FILE="${BIT}.v.pcf"
    QCF_FILE="${BIT}.v.qcf"

    if [ ! -z "{PCF}" ]; then
        PCF_ARGS="--input-pcf ${PCF}"
    else
        PCF_ARGS=""
    fi

    echo "Running fasm2bels"
    python3 ${FASM2BELS} ${BIT} --phy-db ${VPR_DB} --device-name ${FASM2BELS_DEVICE} --package-name ${PART} --input-type bitstream --output-verilog ${VERILOG_FILE} ${PCF_ARGS} --output-pcf ${PCF_FILE} --output-qcf ${QCF_FILE}

else

    echo "ERROR: Unsupported device '${DEVICE}' for fasm2bels"
    exit -1
fi

