set_property PACKAGE_PIN M14 [get_ports led[0]]
set_property PACKAGE_PIN M15 [get_ports led[1]]
set_property PACKAGE_PIN G14 [get_ports led[2]]
set_property PACKAGE_PIN D18 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led*]
set_property PACKAGE_PIN N15 [get_ports tx]
set_property PACKAGE_PIN L14 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN K17 [get_ports clk125]
set_property IOSTANDARD LVCMOS33 [get_ports clk125]

create_clock -name sys_clk -period 20.0 [get_nets sys_clk]
create_clock -name clk -period 20.0 [get_nets clk]
