load('//make:build_defs.bzl', 'n_template', 'v2x')

n_template(
    name = 'carry4_Nxor',
    prefixes = ['a', 'b', 'c', 'd'],
    srcs = ['ntemplate.carry4_Nxor.sim.v'],
    apply_v2x = True,
    visibility = ["//artix7/primitives/slicel/carry4_modes/carry4_split:__pkg__"],
    )
