//--------------------------------------------------------------------------------
// Auto-generated by Migen (e2e6c72) & LiteX (1b07c084) on 2020-02-28 15:59:50
//--------------------------------------------------------------------------------
module litex_core(
	input sys_clk,
	input sys_rst,
	output reg pwm0,
	output reg pwm1,
	output reg pwm2,
	input [29:0] wb_adr,
	input [31:0] wb_dat_w,
	output [31:0] wb_dat_r,
	input [3:0] wb_sel,
	input wb_cyc,
	input wb_stb,
	output wb_ack,
	input wb_we,
	input [2:0] wb_cti,
	input [1:0] wb_bte,
	output wb_err
);

wire sys_clk_1;
wire sys_rst_1;
wire por_clk;
reg main_int_rst = 1'd1;
reg [13:0] main_adr = 14'd0;
reg main_we = 1'd0;
wire [7:0] main_dat_w;
wire [7:0] main_dat_r;
wire [29:0] main_bus_wishbone_adr;
wire [31:0] main_bus_wishbone_dat_w;
wire [31:0] main_bus_wishbone_dat_r;
wire [3:0] main_bus_wishbone_sel;
wire main_bus_wishbone_cyc;
wire main_bus_wishbone_stb;
reg main_bus_wishbone_ack = 1'd0;
wire main_bus_wishbone_we;
wire [2:0] main_bus_wishbone_cti;
wire [1:0] main_bus_wishbone_bte;
reg main_bus_wishbone_err = 1'd0;
wire main_pwm0_enable;
wire [31:0] main_pwm0_width;
wire [31:0] main_pwm0_period;
reg [31:0] main_pwm0_counter = 32'd0;
reg main_pwm0_enable_storage = 1'd0;
reg main_pwm0_enable_re = 1'd0;
reg [31:0] main_pwm0_width_storage = 32'd0;
reg main_pwm0_width_re = 1'd0;
reg [31:0] main_pwm0_period_storage = 32'd0;
reg main_pwm0_period_re = 1'd0;
wire main_pwm1_enable;
wire [31:0] main_pwm1_width;
wire [31:0] main_pwm1_period;
reg [31:0] main_pwm1_counter = 32'd0;
reg main_pwm1_enable_storage = 1'd0;
reg main_pwm1_enable_re = 1'd0;
reg [31:0] main_pwm1_width_storage = 32'd0;
reg main_pwm1_width_re = 1'd0;
reg [31:0] main_pwm1_period_storage = 32'd0;
reg main_pwm1_period_re = 1'd0;
wire main_pwm2_enable;
wire [31:0] main_pwm2_width;
wire [31:0] main_pwm2_period;
reg [31:0] main_pwm2_counter = 32'd0;
reg main_pwm2_enable_storage = 1'd0;
reg main_pwm2_enable_re = 1'd0;
reg [31:0] main_pwm2_width_storage = 32'd0;
reg main_pwm2_width_re = 1'd0;
reg [31:0] main_pwm2_period_storage = 32'd0;
reg main_pwm2_period_re = 1'd0;
wire [29:0] main_wb_bus_adr;
wire [31:0] main_wb_bus_dat_w;
wire [31:0] main_wb_bus_dat_r;
wire [3:0] main_wb_bus_sel;
wire main_wb_bus_cyc;
wire main_wb_bus_stb;
wire main_wb_bus_ack;
wire main_wb_bus_we;
wire [2:0] main_wb_bus_cti;
wire [1:0] main_wb_bus_bte;
wire main_wb_bus_err;
reg builder_state = 1'd0;
reg builder_next_state = 1'd0;
wire [29:0] builder_shared_adr;
wire [31:0] builder_shared_dat_w;
reg [31:0] builder_shared_dat_r = 32'd0;
wire [3:0] builder_shared_sel;
wire builder_shared_cyc;
wire builder_shared_stb;
reg builder_shared_ack = 1'd0;
wire builder_shared_we;
wire [2:0] builder_shared_cti;
wire [1:0] builder_shared_bte;
wire builder_shared_err;
wire builder_request;
wire builder_grant;
wire builder_slave_sel;
reg builder_slave_sel_r = 1'd0;
reg builder_error = 1'd0;
wire builder_wait;
wire builder_done;
reg [19:0] builder_count = 20'd1000000;
wire [13:0] builder_interface0_bank_bus_adr;
wire builder_interface0_bank_bus_we;
wire [7:0] builder_interface0_bank_bus_dat_w;
reg [7:0] builder_interface0_bank_bus_dat_r = 8'd0;
wire builder_csrbank0_enable0_re;
wire builder_csrbank0_enable0_r;
wire builder_csrbank0_enable0_we;
wire builder_csrbank0_enable0_w;
wire builder_csrbank0_width3_re;
wire [7:0] builder_csrbank0_width3_r;
wire builder_csrbank0_width3_we;
wire [7:0] builder_csrbank0_width3_w;
wire builder_csrbank0_width2_re;
wire [7:0] builder_csrbank0_width2_r;
wire builder_csrbank0_width2_we;
wire [7:0] builder_csrbank0_width2_w;
wire builder_csrbank0_width1_re;
wire [7:0] builder_csrbank0_width1_r;
wire builder_csrbank0_width1_we;
wire [7:0] builder_csrbank0_width1_w;
wire builder_csrbank0_width0_re;
wire [7:0] builder_csrbank0_width0_r;
wire builder_csrbank0_width0_we;
wire [7:0] builder_csrbank0_width0_w;
wire builder_csrbank0_period3_re;
wire [7:0] builder_csrbank0_period3_r;
wire builder_csrbank0_period3_we;
wire [7:0] builder_csrbank0_period3_w;
wire builder_csrbank0_period2_re;
wire [7:0] builder_csrbank0_period2_r;
wire builder_csrbank0_period2_we;
wire [7:0] builder_csrbank0_period2_w;
wire builder_csrbank0_period1_re;
wire [7:0] builder_csrbank0_period1_r;
wire builder_csrbank0_period1_we;
wire [7:0] builder_csrbank0_period1_w;
wire builder_csrbank0_period0_re;
wire [7:0] builder_csrbank0_period0_r;
wire builder_csrbank0_period0_we;
wire [7:0] builder_csrbank0_period0_w;
wire builder_csrbank0_sel;
wire [13:0] builder_interface1_bank_bus_adr;
wire builder_interface1_bank_bus_we;
wire [7:0] builder_interface1_bank_bus_dat_w;
reg [7:0] builder_interface1_bank_bus_dat_r = 8'd0;
wire builder_csrbank1_enable0_re;
wire builder_csrbank1_enable0_r;
wire builder_csrbank1_enable0_we;
wire builder_csrbank1_enable0_w;
wire builder_csrbank1_width3_re;
wire [7:0] builder_csrbank1_width3_r;
wire builder_csrbank1_width3_we;
wire [7:0] builder_csrbank1_width3_w;
wire builder_csrbank1_width2_re;
wire [7:0] builder_csrbank1_width2_r;
wire builder_csrbank1_width2_we;
wire [7:0] builder_csrbank1_width2_w;
wire builder_csrbank1_width1_re;
wire [7:0] builder_csrbank1_width1_r;
wire builder_csrbank1_width1_we;
wire [7:0] builder_csrbank1_width1_w;
wire builder_csrbank1_width0_re;
wire [7:0] builder_csrbank1_width0_r;
wire builder_csrbank1_width0_we;
wire [7:0] builder_csrbank1_width0_w;
wire builder_csrbank1_period3_re;
wire [7:0] builder_csrbank1_period3_r;
wire builder_csrbank1_period3_we;
wire [7:0] builder_csrbank1_period3_w;
wire builder_csrbank1_period2_re;
wire [7:0] builder_csrbank1_period2_r;
wire builder_csrbank1_period2_we;
wire [7:0] builder_csrbank1_period2_w;
wire builder_csrbank1_period1_re;
wire [7:0] builder_csrbank1_period1_r;
wire builder_csrbank1_period1_we;
wire [7:0] builder_csrbank1_period1_w;
wire builder_csrbank1_period0_re;
wire [7:0] builder_csrbank1_period0_r;
wire builder_csrbank1_period0_we;
wire [7:0] builder_csrbank1_period0_w;
wire builder_csrbank1_sel;
wire [13:0] builder_interface2_bank_bus_adr;
wire builder_interface2_bank_bus_we;
wire [7:0] builder_interface2_bank_bus_dat_w;
reg [7:0] builder_interface2_bank_bus_dat_r = 8'd0;
wire builder_csrbank2_enable0_re;
wire builder_csrbank2_enable0_r;
wire builder_csrbank2_enable0_we;
wire builder_csrbank2_enable0_w;
wire builder_csrbank2_width3_re;
wire [7:0] builder_csrbank2_width3_r;
wire builder_csrbank2_width3_we;
wire [7:0] builder_csrbank2_width3_w;
wire builder_csrbank2_width2_re;
wire [7:0] builder_csrbank2_width2_r;
wire builder_csrbank2_width2_we;
wire [7:0] builder_csrbank2_width2_w;
wire builder_csrbank2_width1_re;
wire [7:0] builder_csrbank2_width1_r;
wire builder_csrbank2_width1_we;
wire [7:0] builder_csrbank2_width1_w;
wire builder_csrbank2_width0_re;
wire [7:0] builder_csrbank2_width0_r;
wire builder_csrbank2_width0_we;
wire [7:0] builder_csrbank2_width0_w;
wire builder_csrbank2_period3_re;
wire [7:0] builder_csrbank2_period3_r;
wire builder_csrbank2_period3_we;
wire [7:0] builder_csrbank2_period3_w;
wire builder_csrbank2_period2_re;
wire [7:0] builder_csrbank2_period2_r;
wire builder_csrbank2_period2_we;
wire [7:0] builder_csrbank2_period2_w;
wire builder_csrbank2_period1_re;
wire [7:0] builder_csrbank2_period1_r;
wire builder_csrbank2_period1_we;
wire [7:0] builder_csrbank2_period1_w;
wire builder_csrbank2_period0_re;
wire [7:0] builder_csrbank2_period0_r;
wire builder_csrbank2_period0_we;
wire [7:0] builder_csrbank2_period0_w;
wire builder_csrbank2_sel;
wire [13:0] builder_adr;
wire builder_we;
wire [7:0] builder_dat_w;
wire [7:0] builder_dat_r;
reg [29:0] builder_array_muxed0 = 30'd0;
reg [31:0] builder_array_muxed1 = 32'd0;
reg [3:0] builder_array_muxed2 = 4'd0;
reg builder_array_muxed3 = 1'd0;
reg builder_array_muxed4 = 1'd0;
reg builder_array_muxed5 = 1'd0;
reg [2:0] builder_array_muxed6 = 3'd0;
reg [1:0] builder_array_muxed7 = 2'd0;

assign main_wb_bus_adr = wb_adr;
assign main_wb_bus_dat_w = wb_dat_w;
assign wb_dat_r = main_wb_bus_dat_r;
assign main_wb_bus_sel = wb_sel;
assign main_wb_bus_cyc = wb_cyc;
assign main_wb_bus_stb = wb_stb;
assign wb_ack = main_wb_bus_ack;
assign main_wb_bus_we = wb_we;
assign main_wb_bus_cti = wb_cti;
assign main_wb_bus_bte = wb_bte;
assign wb_err = main_wb_bus_err;
assign sys_clk_1 = sys_clk;
assign por_clk = sys_clk;
assign sys_rst_1 = main_int_rst;
assign main_dat_w = main_bus_wishbone_dat_w;
assign main_bus_wishbone_dat_r = main_dat_r;
always @(*) begin
	main_we <= 1'd0;
	builder_next_state <= 1'd0;
	main_bus_wishbone_ack <= 1'd0;
	main_adr <= 14'd0;
	builder_next_state <= builder_state;
	case (builder_state)
		1'd1: begin
			main_bus_wishbone_ack <= 1'd1;
			builder_next_state <= 1'd0;
		end
		default: begin
			if ((main_bus_wishbone_cyc & main_bus_wishbone_stb)) begin
				main_adr <= main_bus_wishbone_adr;
				main_we <= main_bus_wishbone_we;
				builder_next_state <= 1'd1;
			end
		end
	endcase
end
assign builder_shared_adr = builder_array_muxed0;
assign builder_shared_dat_w = builder_array_muxed1;
assign builder_shared_sel = builder_array_muxed2;
assign builder_shared_cyc = builder_array_muxed3;
assign builder_shared_stb = builder_array_muxed4;
assign builder_shared_we = builder_array_muxed5;
assign builder_shared_cti = builder_array_muxed6;
assign builder_shared_bte = builder_array_muxed7;
assign main_wb_bus_dat_r = builder_shared_dat_r;
assign main_wb_bus_ack = (builder_shared_ack & (builder_grant == 1'd0));
assign main_wb_bus_err = (builder_shared_err & (builder_grant == 1'd0));
assign builder_request = {main_wb_bus_cyc};
assign builder_grant = 1'd0;
assign builder_slave_sel = (builder_shared_adr[29:14] == 1'd0);
assign main_bus_wishbone_adr = builder_shared_adr;
assign main_bus_wishbone_dat_w = builder_shared_dat_w;
assign main_bus_wishbone_sel = builder_shared_sel;
assign main_bus_wishbone_stb = builder_shared_stb;
assign main_bus_wishbone_we = builder_shared_we;
assign main_bus_wishbone_cti = builder_shared_cti;
assign main_bus_wishbone_bte = builder_shared_bte;
assign main_bus_wishbone_cyc = (builder_shared_cyc & builder_slave_sel);
assign builder_shared_err = main_bus_wishbone_err;
assign builder_wait = ((builder_shared_stb & builder_shared_cyc) & (~builder_shared_ack));
always @(*) begin
	builder_error <= 1'd0;
	builder_shared_ack <= 1'd0;
	builder_shared_dat_r <= 32'd0;
	builder_shared_ack <= main_bus_wishbone_ack;
	builder_shared_dat_r <= ({32{builder_slave_sel_r}} & main_bus_wishbone_dat_r);
	if (builder_done) begin
		builder_shared_dat_r <= 32'd4294967295;
		builder_shared_ack <= 1'd1;
		builder_error <= 1'd1;
	end
end
assign builder_done = (builder_count == 1'd0);
assign builder_csrbank0_sel = (builder_interface0_bank_bus_adr[13:9] == 1'd0);
assign builder_csrbank0_enable0_r = builder_interface0_bank_bus_dat_w[0];
assign builder_csrbank0_enable0_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 1'd0));
assign builder_csrbank0_enable0_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 1'd0));
assign builder_csrbank0_width3_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_width3_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 1'd1));
assign builder_csrbank0_width3_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 1'd1));
assign builder_csrbank0_width2_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_width2_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 2'd2));
assign builder_csrbank0_width2_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 2'd2));
assign builder_csrbank0_width1_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_width1_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 2'd3));
assign builder_csrbank0_width1_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 2'd3));
assign builder_csrbank0_width0_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_width0_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 3'd4));
assign builder_csrbank0_width0_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 3'd4));
assign builder_csrbank0_period3_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_period3_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 3'd5));
assign builder_csrbank0_period3_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 3'd5));
assign builder_csrbank0_period2_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_period2_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 3'd6));
assign builder_csrbank0_period2_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 3'd6));
assign builder_csrbank0_period1_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_period1_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 3'd7));
assign builder_csrbank0_period1_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 3'd7));
assign builder_csrbank0_period0_r = builder_interface0_bank_bus_dat_w[7:0];
assign builder_csrbank0_period0_re = ((builder_csrbank0_sel & builder_interface0_bank_bus_we) & (builder_interface0_bank_bus_adr[3:0] == 4'd8));
assign builder_csrbank0_period0_we = ((builder_csrbank0_sel & (~builder_interface0_bank_bus_we)) & (builder_interface0_bank_bus_adr[3:0] == 4'd8));
assign builder_csrbank0_enable0_w = main_pwm0_enable_storage;
assign builder_csrbank0_width3_w = main_pwm0_width_storage[31:24];
assign builder_csrbank0_width2_w = main_pwm0_width_storage[23:16];
assign builder_csrbank0_width1_w = main_pwm0_width_storage[15:8];
assign builder_csrbank0_width0_w = main_pwm0_width_storage[7:0];
assign builder_csrbank0_period3_w = main_pwm0_period_storage[31:24];
assign builder_csrbank0_period2_w = main_pwm0_period_storage[23:16];
assign builder_csrbank0_period1_w = main_pwm0_period_storage[15:8];
assign builder_csrbank0_period0_w = main_pwm0_period_storage[7:0];
assign builder_csrbank1_sel = (builder_interface1_bank_bus_adr[13:9] == 1'd1);
assign builder_csrbank1_enable0_r = builder_interface1_bank_bus_dat_w[0];
assign builder_csrbank1_enable0_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 1'd0));
assign builder_csrbank1_enable0_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 1'd0));
assign builder_csrbank1_width3_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_width3_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 1'd1));
assign builder_csrbank1_width3_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 1'd1));
assign builder_csrbank1_width2_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_width2_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 2'd2));
assign builder_csrbank1_width2_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 2'd2));
assign builder_csrbank1_width1_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_width1_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 2'd3));
assign builder_csrbank1_width1_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 2'd3));
assign builder_csrbank1_width0_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_width0_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 3'd4));
assign builder_csrbank1_width0_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 3'd4));
assign builder_csrbank1_period3_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_period3_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 3'd5));
assign builder_csrbank1_period3_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 3'd5));
assign builder_csrbank1_period2_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_period2_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 3'd6));
assign builder_csrbank1_period2_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 3'd6));
assign builder_csrbank1_period1_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_period1_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 3'd7));
assign builder_csrbank1_period1_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 3'd7));
assign builder_csrbank1_period0_r = builder_interface1_bank_bus_dat_w[7:0];
assign builder_csrbank1_period0_re = ((builder_csrbank1_sel & builder_interface1_bank_bus_we) & (builder_interface1_bank_bus_adr[3:0] == 4'd8));
assign builder_csrbank1_period0_we = ((builder_csrbank1_sel & (~builder_interface1_bank_bus_we)) & (builder_interface1_bank_bus_adr[3:0] == 4'd8));
assign builder_csrbank1_enable0_w = main_pwm1_enable_storage;
assign builder_csrbank1_width3_w = main_pwm1_width_storage[31:24];
assign builder_csrbank1_width2_w = main_pwm1_width_storage[23:16];
assign builder_csrbank1_width1_w = main_pwm1_width_storage[15:8];
assign builder_csrbank1_width0_w = main_pwm1_width_storage[7:0];
assign builder_csrbank1_period3_w = main_pwm1_period_storage[31:24];
assign builder_csrbank1_period2_w = main_pwm1_period_storage[23:16];
assign builder_csrbank1_period1_w = main_pwm1_period_storage[15:8];
assign builder_csrbank1_period0_w = main_pwm1_period_storage[7:0];
assign builder_csrbank2_sel = (builder_interface2_bank_bus_adr[13:9] == 2'd2);
assign builder_csrbank2_enable0_r = builder_interface2_bank_bus_dat_w[0];
assign builder_csrbank2_enable0_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 1'd0));
assign builder_csrbank2_enable0_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 1'd0));
assign builder_csrbank2_width3_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_width3_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 1'd1));
assign builder_csrbank2_width3_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 1'd1));
assign builder_csrbank2_width2_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_width2_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 2'd2));
assign builder_csrbank2_width2_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 2'd2));
assign builder_csrbank2_width1_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_width1_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 2'd3));
assign builder_csrbank2_width1_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 2'd3));
assign builder_csrbank2_width0_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_width0_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 3'd4));
assign builder_csrbank2_width0_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 3'd4));
assign builder_csrbank2_period3_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_period3_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 3'd5));
assign builder_csrbank2_period3_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 3'd5));
assign builder_csrbank2_period2_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_period2_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 3'd6));
assign builder_csrbank2_period2_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 3'd6));
assign builder_csrbank2_period1_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_period1_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 3'd7));
assign builder_csrbank2_period1_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 3'd7));
assign builder_csrbank2_period0_r = builder_interface2_bank_bus_dat_w[7:0];
assign builder_csrbank2_period0_re = ((builder_csrbank2_sel & builder_interface2_bank_bus_we) & (builder_interface2_bank_bus_adr[3:0] == 4'd8));
assign builder_csrbank2_period0_we = ((builder_csrbank2_sel & (~builder_interface2_bank_bus_we)) & (builder_interface2_bank_bus_adr[3:0] == 4'd8));
assign builder_csrbank2_enable0_w = main_pwm2_enable_storage;
assign builder_csrbank2_width3_w = main_pwm2_width_storage[31:24];
assign builder_csrbank2_width2_w = main_pwm2_width_storage[23:16];
assign builder_csrbank2_width1_w = main_pwm2_width_storage[15:8];
assign builder_csrbank2_width0_w = main_pwm2_width_storage[7:0];
assign builder_csrbank2_period3_w = main_pwm2_period_storage[31:24];
assign builder_csrbank2_period2_w = main_pwm2_period_storage[23:16];
assign builder_csrbank2_period1_w = main_pwm2_period_storage[15:8];
assign builder_csrbank2_period0_w = main_pwm2_period_storage[7:0];
assign builder_adr = main_adr;
assign builder_we = main_we;
assign builder_dat_w = main_dat_w;
assign main_dat_r = builder_dat_r;
assign builder_interface0_bank_bus_adr = builder_adr;
assign builder_interface1_bank_bus_adr = builder_adr;
assign builder_interface2_bank_bus_adr = builder_adr;
assign builder_interface0_bank_bus_we = builder_we;
assign builder_interface1_bank_bus_we = builder_we;
assign builder_interface2_bank_bus_we = builder_we;
assign builder_interface0_bank_bus_dat_w = builder_dat_w;
assign builder_interface1_bank_bus_dat_w = builder_dat_w;
assign builder_interface2_bank_bus_dat_w = builder_dat_w;
assign builder_dat_r = ((builder_interface0_bank_bus_dat_r | builder_interface1_bank_bus_dat_r) | builder_interface2_bank_bus_dat_r);
always @(*) begin
	builder_array_muxed0 <= 30'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed0 <= main_wb_bus_adr;
		end
	endcase
end
always @(*) begin
	builder_array_muxed1 <= 32'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed1 <= main_wb_bus_dat_w;
		end
	endcase
end
always @(*) begin
	builder_array_muxed2 <= 4'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed2 <= main_wb_bus_sel;
		end
	endcase
end
always @(*) begin
	builder_array_muxed3 <= 1'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed3 <= main_wb_bus_cyc;
		end
	endcase
end
always @(*) begin
	builder_array_muxed4 <= 1'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed4 <= main_wb_bus_stb;
		end
	endcase
end
always @(*) begin
	builder_array_muxed5 <= 1'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed5 <= main_wb_bus_we;
		end
	endcase
end
always @(*) begin
	builder_array_muxed6 <= 3'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed6 <= main_wb_bus_cti;
		end
	endcase
end
always @(*) begin
	builder_array_muxed7 <= 2'd0;
	case (builder_grant)
		default: begin
			builder_array_muxed7 <= main_wb_bus_bte;
		end
	endcase
end
assign main_pwm0_enable = main_pwm0_enable_storage;
assign main_pwm0_width = main_pwm0_width_storage;
assign main_pwm0_period = main_pwm0_period_storage;
assign main_pwm1_enable = main_pwm1_enable_storage;
assign main_pwm1_width = main_pwm1_width_storage;
assign main_pwm1_period = main_pwm1_period_storage;
assign main_pwm2_enable = main_pwm2_enable_storage;
assign main_pwm2_width = main_pwm2_width_storage;
assign main_pwm2_period = main_pwm2_period_storage;

always @(posedge por_clk) begin
	main_int_rst <= sys_rst;
end

always @(posedge sys_clk_1) begin
	builder_state <= builder_next_state;
	if (main_pwm0_enable) begin
		main_pwm0_counter <= (main_pwm0_counter + 1'd1);
		if ((main_pwm0_counter < main_pwm0_width)) begin
			pwm0 <= 1'd1;
		end else begin
			pwm0 <= 1'd0;
		end
		if ((main_pwm0_counter == (main_pwm0_period - 1'd1))) begin
			main_pwm0_counter <= 1'd0;
		end
	end else begin
		main_pwm0_counter <= 1'd0;
		pwm0 <= 1'd0;
	end
	if (main_pwm1_enable) begin
		main_pwm1_counter <= (main_pwm1_counter + 1'd1);
		if ((main_pwm1_counter < main_pwm1_width)) begin
			pwm1 <= 1'd1;
		end else begin
			pwm1 <= 1'd0;
		end
		if ((main_pwm1_counter == (main_pwm1_period - 1'd1))) begin
			main_pwm1_counter <= 1'd0;
		end
	end else begin
		main_pwm1_counter <= 1'd0;
		pwm1 <= 1'd0;
	end
	if (main_pwm2_enable) begin
		main_pwm2_counter <= (main_pwm2_counter + 1'd1);
		if ((main_pwm2_counter < main_pwm2_width)) begin
			pwm2 <= 1'd1;
		end else begin
			pwm2 <= 1'd0;
		end
		if ((main_pwm2_counter == (main_pwm2_period - 1'd1))) begin
			main_pwm2_counter <= 1'd0;
		end
	end else begin
		main_pwm2_counter <= 1'd0;
		pwm2 <= 1'd0;
	end
	builder_slave_sel_r <= builder_slave_sel;
	if (builder_wait) begin
		if ((~builder_done)) begin
			builder_count <= (builder_count - 1'd1);
		end
	end else begin
		builder_count <= 20'd1000000;
	end
	builder_interface0_bank_bus_dat_r <= 1'd0;
	if (builder_csrbank0_sel) begin
		case (builder_interface0_bank_bus_adr[3:0])
			1'd0: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_enable0_w;
			end
			1'd1: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_width3_w;
			end
			2'd2: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_width2_w;
			end
			2'd3: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_width1_w;
			end
			3'd4: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_width0_w;
			end
			3'd5: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_period3_w;
			end
			3'd6: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_period2_w;
			end
			3'd7: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_period1_w;
			end
			4'd8: begin
				builder_interface0_bank_bus_dat_r <= builder_csrbank0_period0_w;
			end
		endcase
	end
	if (builder_csrbank0_enable0_re) begin
		main_pwm0_enable_storage <= builder_csrbank0_enable0_r;
	end
	main_pwm0_enable_re <= builder_csrbank0_enable0_re;
	if (builder_csrbank0_width3_re) begin
		main_pwm0_width_storage[31:24] <= builder_csrbank0_width3_r;
	end
	if (builder_csrbank0_width2_re) begin
		main_pwm0_width_storage[23:16] <= builder_csrbank0_width2_r;
	end
	if (builder_csrbank0_width1_re) begin
		main_pwm0_width_storage[15:8] <= builder_csrbank0_width1_r;
	end
	if (builder_csrbank0_width0_re) begin
		main_pwm0_width_storage[7:0] <= builder_csrbank0_width0_r;
	end
	main_pwm0_width_re <= builder_csrbank0_width0_re;
	if (builder_csrbank0_period3_re) begin
		main_pwm0_period_storage[31:24] <= builder_csrbank0_period3_r;
	end
	if (builder_csrbank0_period2_re) begin
		main_pwm0_period_storage[23:16] <= builder_csrbank0_period2_r;
	end
	if (builder_csrbank0_period1_re) begin
		main_pwm0_period_storage[15:8] <= builder_csrbank0_period1_r;
	end
	if (builder_csrbank0_period0_re) begin
		main_pwm0_period_storage[7:0] <= builder_csrbank0_period0_r;
	end
	main_pwm0_period_re <= builder_csrbank0_period0_re;
	builder_interface1_bank_bus_dat_r <= 1'd0;
	if (builder_csrbank1_sel) begin
		case (builder_interface1_bank_bus_adr[3:0])
			1'd0: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_enable0_w;
			end
			1'd1: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_width3_w;
			end
			2'd2: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_width2_w;
			end
			2'd3: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_width1_w;
			end
			3'd4: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_width0_w;
			end
			3'd5: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_period3_w;
			end
			3'd6: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_period2_w;
			end
			3'd7: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_period1_w;
			end
			4'd8: begin
				builder_interface1_bank_bus_dat_r <= builder_csrbank1_period0_w;
			end
		endcase
	end
	if (builder_csrbank1_enable0_re) begin
		main_pwm1_enable_storage <= builder_csrbank1_enable0_r;
	end
	main_pwm1_enable_re <= builder_csrbank1_enable0_re;
	if (builder_csrbank1_width3_re) begin
		main_pwm1_width_storage[31:24] <= builder_csrbank1_width3_r;
	end
	if (builder_csrbank1_width2_re) begin
		main_pwm1_width_storage[23:16] <= builder_csrbank1_width2_r;
	end
	if (builder_csrbank1_width1_re) begin
		main_pwm1_width_storage[15:8] <= builder_csrbank1_width1_r;
	end
	if (builder_csrbank1_width0_re) begin
		main_pwm1_width_storage[7:0] <= builder_csrbank1_width0_r;
	end
	main_pwm1_width_re <= builder_csrbank1_width0_re;
	if (builder_csrbank1_period3_re) begin
		main_pwm1_period_storage[31:24] <= builder_csrbank1_period3_r;
	end
	if (builder_csrbank1_period2_re) begin
		main_pwm1_period_storage[23:16] <= builder_csrbank1_period2_r;
	end
	if (builder_csrbank1_period1_re) begin
		main_pwm1_period_storage[15:8] <= builder_csrbank1_period1_r;
	end
	if (builder_csrbank1_period0_re) begin
		main_pwm1_period_storage[7:0] <= builder_csrbank1_period0_r;
	end
	main_pwm1_period_re <= builder_csrbank1_period0_re;
	builder_interface2_bank_bus_dat_r <= 1'd0;
	if (builder_csrbank2_sel) begin
		case (builder_interface2_bank_bus_adr[3:0])
			1'd0: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_enable0_w;
			end
			1'd1: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_width3_w;
			end
			2'd2: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_width2_w;
			end
			2'd3: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_width1_w;
			end
			3'd4: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_width0_w;
			end
			3'd5: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_period3_w;
			end
			3'd6: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_period2_w;
			end
			3'd7: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_period1_w;
			end
			4'd8: begin
				builder_interface2_bank_bus_dat_r <= builder_csrbank2_period0_w;
			end
		endcase
	end
	if (builder_csrbank2_enable0_re) begin
		main_pwm2_enable_storage <= builder_csrbank2_enable0_r;
	end
	main_pwm2_enable_re <= builder_csrbank2_enable0_re;
	if (builder_csrbank2_width3_re) begin
		main_pwm2_width_storage[31:24] <= builder_csrbank2_width3_r;
	end
	if (builder_csrbank2_width2_re) begin
		main_pwm2_width_storage[23:16] <= builder_csrbank2_width2_r;
	end
	if (builder_csrbank2_width1_re) begin
		main_pwm2_width_storage[15:8] <= builder_csrbank2_width1_r;
	end
	if (builder_csrbank2_width0_re) begin
		main_pwm2_width_storage[7:0] <= builder_csrbank2_width0_r;
	end
	main_pwm2_width_re <= builder_csrbank2_width0_re;
	if (builder_csrbank2_period3_re) begin
		main_pwm2_period_storage[31:24] <= builder_csrbank2_period3_r;
	end
	if (builder_csrbank2_period2_re) begin
		main_pwm2_period_storage[23:16] <= builder_csrbank2_period2_r;
	end
	if (builder_csrbank2_period1_re) begin
		main_pwm2_period_storage[15:8] <= builder_csrbank2_period1_r;
	end
	if (builder_csrbank2_period0_re) begin
		main_pwm2_period_storage[7:0] <= builder_csrbank2_period0_r;
	end
	main_pwm2_period_re <= builder_csrbank2_period0_re;
	if (sys_rst_1) begin
		pwm0 <= 1'd0;
		main_pwm0_counter <= 32'd0;
		main_pwm0_enable_storage <= 1'd0;
		main_pwm0_enable_re <= 1'd0;
		main_pwm0_width_storage <= 32'd0;
		main_pwm0_width_re <= 1'd0;
		main_pwm0_period_storage <= 32'd0;
		main_pwm0_period_re <= 1'd0;
		pwm1 <= 1'd0;
		main_pwm1_counter <= 32'd0;
		main_pwm1_enable_storage <= 1'd0;
		main_pwm1_enable_re <= 1'd0;
		main_pwm1_width_storage <= 32'd0;
		main_pwm1_width_re <= 1'd0;
		main_pwm1_period_storage <= 32'd0;
		main_pwm1_period_re <= 1'd0;
		pwm2 <= 1'd0;
		main_pwm2_counter <= 32'd0;
		main_pwm2_enable_storage <= 1'd0;
		main_pwm2_enable_re <= 1'd0;
		main_pwm2_width_storage <= 32'd0;
		main_pwm2_width_re <= 1'd0;
		main_pwm2_period_storage <= 32'd0;
		main_pwm2_period_re <= 1'd0;
		builder_state <= 1'd0;
		builder_slave_sel_r <= 1'd0;
		builder_count <= 20'd1000000;
		builder_interface0_bank_bus_dat_r <= 8'd0;
		builder_interface1_bank_bus_dat_r <= 8'd0;
		builder_interface2_bank_bus_dat_r <= 8'd0;
	end
end

endmodule
