function(DEFINE_QUICKLOGIC_TOOLCHAIN_TARGET)
  set(options)
  set(oneValueArgs ARCH NAME CONV_SCRIPT SYNTH_SCRIPT BIT_TO_BIN ROUTE_CHAN_WIDTH)
  set(multiVelueArgs VPR_ARCH_ARGS)

  cmake_parse_arguments(
    DEFINE_QUICKLOGIC_TOOLCHAIN_TARGET
    "${options}"
    "${oneValueArgs}"
    "${multiValueArgs}"
    "${ARGN}"
  )

  set(ARCH ${DEFINE_QUICKLOGIC_TOOLCHAIN_TARGET_ARCH})
  set(VPS_ARCH_ARGS ${DEFINE_QUICKLOGIC_TOOLCHAIN_TARGET_VPR_ARCH_ARGS})
  set(ROUTE_CHAN_WIDTH ${DEFINE_QUICKLOGIC_TOOLCHAIN_TARGET_ROUTE_CHAN_WIDTH})
  list(JOIN VPR_BASE_ARGS " " VPR_BASE_ARGS)
  string(JOIN " " VPR_ARGS ${VPR_BASE_ARGS} "--route_chan_width ${ROUTE_CHAN_WIDTH}" ${VPR_ARCH_ARGS})
  set(ARCH ${DEFINE_QUICKLOGIC_TOOLCHAIN_TARGET_ARCH})

  get_target_property_required(FASM_TO_BIT ${ARCH} FASM_TO_BIT)

  # install binaries
  install(TARGETS ${DEFINE_XC_TOOLCHAIN_TARGET_BIT_TO_BIN}
          RUNTIME
          DESTINATION bin
          PERMISSIONS WORLD_EXECUTE WORLD_READ OWNER_WRITE OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE)

endfunction()
